import Head from "next/head";
import Image from "next/image";
import { Navbar } from "../components/navbar";
import { useState } from "react";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { Link as ScrollLink } from "react-scroll";

const LandingSection = () => {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <div className="bg-[#DCDDDF] transition-colors duration-1000 dark:bg-[#2A4C65] z-0">
        <Head>
          <title>Christopher Luu Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar currentPage="Home" />
        <div className="flex flex-col items-center sm:justify-center sm:flex-row text-justify relative ">
          <Image
            src="/chrluu high res-modified.png"
            alt="/"
            width="250"
            height="250"
            layoutfill="true"
            wrapper="h-60  w-1/2 bg-red-100 relative flex justify-center"
          />
        </div>
        <section>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <div className="pt-2">
              <a>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-4xl dark:text-white"
                />
              </a>
            </div>

            <a
              target="_blank"
              href="https://github.com/christopher-luu97"
              rel="noopener noreferrer"
            >
              <AiFillGithub className="cursor-pointer" />
            </a>
            <a
              target="_blank"
              href="https://www.linkedin.com/in/christopher-luu-542691149/"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin className="cursor-pointer" />
            </a>
          </div>
          <div className="relative w-full m-auto flex justify-center text-center flex-col items-center z-1">
            <h2 className="text-5xl py-2 text-sky-600 font-medium md:text-6xl dark:text-[#B3CAD8]">
              Christopher Luu
            </h2>
            <h3 className="text-2xl font-bold py-2 md:text-3xl dark:text-white">
              Engineer | Software Developer | Consultant
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
              Professional Engineer working as a Consultant within Data Science.
              I develop software leveraging AI to augment decision making and
              enhance efficiency for clients. Look below to see my skills and
              projects!
            </p>
            <ScrollLink
              activeClass="active"
              to="skillsExperience"
              spy={true}
              offset={-30}
              smooth={true}
              duration={500}
            >
              {" "}
              <div classname="py-10">
                <div
                  className="cursor-pointer font-bold whitespace-nowrap px-10 py-4 border-2 
            text-xl rounded-full border-gray-500 text-gray-500
             hover:border-black hover:text-black dark:hover:text-white dark:hover:border-white"
                >
                  Tell me more
                </div>
              </div>
            </ScrollLink>
          </div>
        </section>
      </div>
    </div>
  );
};

export default LandingSection;
