/** From: https://braydentw.io/ */
import Head from "next/head";
import Link from "next/link";
import { ScrollToTop } from "../hooks/ScrollToTop";
import Projects from "../components/projects";
import Footer from "../components/Footer";
import LandingSection from "../components/LandingSection";
import SkillsSection from "../components/SkillsSection";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [showModal, setShowModal] = useState(false);

  return (
    <div
      className="w-full m-auto flex flex-col items-center justify-center min-h-screen bg-[#DCDDDF]"
      style={{ maxWidth: "2100px" }}
    >
      <div
        className="w-full m-auto flex flex-col items-center justify-center min-h-screen"
        style={{ maxWidth: "1400px" }}
      >
        <Head>
          <title>Christopher Luu Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="px-10 md:px-20 lg:px-40">
          <LandingSection darkMode={darkMode} setDarkMode={setDarkMode} />
          <div className="py-10">
            <SkillsSection />
          </div>
          <section>
            <div className="shadow-lg rounded-3xl shadow-[#75809C] bg-[#F2EEED] dark:bg-[#37668a] dark:shadow-[#E3E7EA]">
              <div className="flex flex-col gap-10 py-2 lg:flex-row lg:flex-wrap">
                <Projects />
                <Link href="/projects"></Link>
              </div>
              <div className="relative w-full pb-5 m-auto flex justify-center text-center flex-col items-center z-1">
                <div
                  className="cursor-pointer font-bold whitespace-nowrap px-10 py-4 border-2 text-center 
                    text-xl rounded-full border-gray-500 text-gray-500
                     hover:border-black hover:text-black dark:hover:text-white dark:hover:border-white"
                >
                  <a target="_blank" href="/projects" rel="noopener noreferrer">
                    View All
                  </a>
                </div>
              </div>
            </div>
            <ScrollToTop />
          </section>
          <div className="pb-10"></div>
        </main>
        <Footer />
      </div>
    </div>
  );
}
